### ISSUE TITLE
Issue with tutorial example code

### ISSUE THREAD

**Issue by deepblue8581** [cosanlab/py-feat#206] opened 2024-02-14 15:15 UTC
I'm attempting to run this example code from the tutorial on my local Pycharm.
![GIThelp](https://github.com/cosanlab/py-feat/assets/62752966/d6e18a7b-0a31-49bd-9e5f-3d277d19b5b2)

However, my program does not generate an image, (See below)
![image2](https://github.com/cosanlab/py-feat/assets/62752966/14992116-49c0-4ef8-8f0f-b8c53ad4f8f1)

To ensure the program is using the correct photo directory I've used print().    (Below)
![image3](https://github.com/cosanlab/py-feat/assets/62752966/22581038-76b5-4204-845f-7af8e0da05ec)

I don't receive any errors, just a "Process finished with exit code 0" and I should have an image which should pop up like the example

Any help on the matter would be greatly appreciated thank you!

Environment:
Python version: 3.8.0
SciPy version: 1.10.1
Py-Feat version: 0.6.1
Operating System: WIndows 10

**Comment by deepblue8581** [comment] 2024-02-14 16:38
Please note this same issue occurs when doing the video detection tutorial code and there is no issue with the directory files

![videoerror](https://github.com/cosanlab/py-feat/assets/62752966/e7bf1a33-0ab2-4e46-8702-1d0a5630c031)

**Comment by sucv** [comment] 2024-03-20 07:22
Hi, I am just a passerby.

The issue is caused by the IDE, which is PyCharm.  In jupyter notebook, the plot will be shown. But in PyCharm, you need extra calls to show it.

Maybe adding the following code after your `imshow()` will show the image.

```
import matplotlib.pyplot as plt
plt.show()
```

**Comment by ejolly** [comment] 2024-03-29 20:14
Thanks @sucv! Yes @deepblue8581 this seems to be an issue with your IDE not py-feat so I'm going to close this

**Closed by ejolly** 2024-03-29 20:14 UTC
